### ISSUE TITLE
I get AttributeError: module 'itree' has no attribute 'Node'

### ISSUE THREAD

**Issue by Keno42** [juncongmoo/itree#22]
Hi,
after installing `itree`, I get an AttributeError when I call `itree.Node` as the following:
```
>>> import itree
>>> itree.Node('fruit', 0, 40)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'itree' has no attribute 'Node'
```
I tried both `pip install itree` and `pip install https://github.com/juncongmoo/itree/archive/refs/tags/v0.0.18.tar.gz`.
Environment: MacBook Pro, Apple M2 Pro, macOS Ventura 13.2.1, Python 3.11.2

**Comment by kowalgregy** [comment]
Also getting this on Win10, have u been able to solve it?

**Comment by juncongmoo** [comment]
You need to uninstall other itree packages, and also make sure there is not a folder called `itree` in your current directory. It should work fine like:

![image](https://user-images.githubusercontent.com/94136485/230799747-5dca1787-776a-4ffc-a276-df7be75e0e05.png)

**Comment by Keno42** [comment]
Thank you. I found that `itree` was installed too.
After uninstalling both `itree` and `py-itree`, I confirmed that `import itree` returned an error.
```
>>> import itree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'itree'
```

It worked after executing this part https://github.com/juncongmoo/itree#build-from-source-with-cmake
